#pragma once

#include <windows.h>
#include <winioctl.h>

#ifndef ANYSIZE_ARRAY
#define ANYSIZE_ARRAY 1
#endif

/* ---------- IOCTLs ---------- */

#ifndef IOCTL_STORAGE_FIRMWARE_GET_INFO
#define IOCTL_STORAGE_FIRMWARE_GET_INFO \
    CTL_CODE(IOCTL_STORAGE_BASE, 0x0700, METHOD_BUFFERED, FILE_READ_ACCESS)
#endif

#ifndef IOCTL_STORAGE_FIRMWARE_DOWNLOAD
#define IOCTL_STORAGE_FIRMWARE_DOWNLOAD \
    CTL_CODE(IOCTL_STORAGE_BASE, 0x0701, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#endif

#ifndef IOCTL_STORAGE_FIRMWARE_ACTIVATE
#define IOCTL_STORAGE_FIRMWARE_ACTIVATE \
    CTL_CODE(IOCTL_STORAGE_BASE, 0x0702, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#endif

/* ---------- Flags / constants ---------- */

#ifndef STORAGE_HW_FIRMWARE_REQUEST_FLAG_CONTROLLER
#define STORAGE_HW_FIRMWARE_REQUEST_FLAG_CONTROLLER        0x00000001UL
#endif

#ifndef STORAGE_HW_FIRMWARE_REQUEST_FLAG_FIRST_SEGMENT
#define STORAGE_HW_FIRMWARE_REQUEST_FLAG_FIRST_SEGMENT     0x00000002UL
#endif

#ifndef STORAGE_HW_FIRMWARE_REQUEST_FLAG_LAST_SEGMENT
#define STORAGE_HW_FIRMWARE_REQUEST_FLAG_LAST_SEGMENT      0x00000004UL
#endif

#ifndef STORAGE_HW_FIRMWARE_REQUEST_FLAG_REPLACE_EXISTING_IMAGE
#define STORAGE_HW_FIRMWARE_REQUEST_FLAG_REPLACE_EXISTING_IMAGE 0x00000008UL
#endif

#ifndef STORAGE_HW_FIRMWARE_REQUEST_FLAG_SWITCH_TO_EXISTING_FIRMWARE
#define STORAGE_HW_FIRMWARE_REQUEST_FLAG_SWITCH_TO_EXISTING_FIRMWARE 0x80000000UL
#endif

#ifndef STORAGE_HW_FIRMWARE_INVALID_SLOT
#define STORAGE_HW_FIRMWARE_INVALID_SLOT 0xFF
#endif

#ifndef STORAGE_HW_FIRMWARE_REVISION_LENGTH
#define STORAGE_HW_FIRMWARE_REVISION_LENGTH 16
#endif

/* ---------- Structures ---------- */

#ifndef _STORAGE_HW_FIRMWARE_INFO_QUERY_DEFINED
#define _STORAGE_HW_FIRMWARE_INFO_QUERY_DEFINED
typedef struct _STORAGE_HW_FIRMWARE_INFO_QUERY {
    ULONG Version;
    ULONG Size;
    ULONG Flags;
    ULONG Reserved;
} STORAGE_HW_FIRMWARE_INFO_QUERY, *PSTORAGE_HW_FIRMWARE_INFO_QUERY;
#endif

#ifndef _STORAGE_HW_FIRMWARE_SLOT_INFO_DEFINED
#define _STORAGE_HW_FIRMWARE_SLOT_INFO_DEFINED
typedef struct _STORAGE_HW_FIRMWARE_SLOT_INFO {
    ULONG Version;
    ULONG Size;

    UCHAR SlotNumber;
    UCHAR ReadOnly : 1;
    UCHAR Reserved0 : 7;
    UCHAR Reserved1[6];

    UCHAR Revision[STORAGE_HW_FIRMWARE_REVISION_LENGTH];
} STORAGE_HW_FIRMWARE_SLOT_INFO, *PSTORAGE_HW_FIRMWARE_SLOT_INFO;
#endif

#ifndef _STORAGE_HW_FIRMWARE_INFO_DEFINED
#define _STORAGE_HW_FIRMWARE_INFO_DEFINED
typedef struct _STORAGE_HW_FIRMWARE_INFO {
    ULONG Version;
    ULONG Size;

    UCHAR SupportUpgrade : 1;
    UCHAR Reserved0      : 7;
    UCHAR SlotCount;
    UCHAR ActiveSlot;
    UCHAR PendingActivateSlot;
    BOOLEAN FirmwareShared;
    UCHAR Reserved[3];

    ULONG ImagePayloadAlignment;
    ULONG ImagePayloadMaxSize;

    STORAGE_HW_FIRMWARE_SLOT_INFO Slot[ANYSIZE_ARRAY];
} STORAGE_HW_FIRMWARE_INFO, *PSTORAGE_HW_FIRMWARE_INFO;
#endif

#ifndef _STORAGE_HW_FIRMWARE_DOWNLOAD_DEFINED
#define _STORAGE_HW_FIRMWARE_DOWNLOAD_DEFINED
typedef struct _STORAGE_HW_FIRMWARE_DOWNLOAD {
    ULONG     Version;
    ULONG     Size;

    ULONG     Flags;
    UCHAR     Slot;
    UCHAR     Reserved[3];

    ULONGLONG Offset;
    ULONGLONG BufferSize;

    UCHAR     ImageBuffer[ANYSIZE_ARRAY];
} STORAGE_HW_FIRMWARE_DOWNLOAD, *PSTORAGE_HW_FIRMWARE_DOWNLOAD;
#endif

#ifndef _STORAGE_HW_FIRMWARE_ACTIVATE_DEFINED
#define _STORAGE_HW_FIRMWARE_ACTIVATE_DEFINED
typedef struct _STORAGE_HW_FIRMWARE_ACTIVATE {
    ULONG Version;
    ULONG Size;

    ULONG Flags;
    UCHAR Slot;
    UCHAR Reserved0[3];
} STORAGE_HW_FIRMWARE_ACTIVATE, *PSTORAGE_HW_FIRMWARE_ACTIVATE;
#endif
